use base;

CREATE TABLE `user`
(
    id         INTEGER PRIMARY KEY AUTO_INCREMENT,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DESC user;

DESCRIBE user;

SHOW FULL COLUMNS FROM user;

SHOW CREATE TABLE user;

SHOW TABLE STATUS FROM base;

SHOW PLUGINS;
